
const actionType = {

    // DOCUMENT SECTION
    ADD_DOCUMENT : "ADD_DOCUMENT",
    ADD_DOCUMENT_ERROR: "ADD_DOCUMENT_ERROR",
    UPDATE_DOCUMENT: "UPDATE_DOCUMENT",
    UPDATE_DOCUMENT_ERROR: "UPDATE_DOCUMENT_ERROR",
    

    // CONTACT SECTION
    SET_CONTACT_SECTION: "SET_CONTACT_SECTION",
    SET_CONTACT_SECTION_ERROR: "SET_CONTACT_SECTION_ERROR",
    UPDATE_CONTACT_SECTION: "UPDATE_CONTACT_SECTION",
    UPDATE_CONTACT_SECTION_ERROR: "UPDATE_CONTACT_SECTION_ERROR",
    

    //EDUCATION SECTION
    SET_EDU_SECTION: "SET_EDU_SECTION",
    SET_EDU_SECTION_ERROR: "SET_EDU_SECTION_ERROR",
    UPDATE_EDU_SECTION : "UPDATE_EDU_SECTION",
    UPDATE_EDU_SECTION_ERROR: "UPDATE_EDU_SECTION_ERROR",
    

    // AUTH SECTION
    USER_SIGN_IN: "USER_SIGN_IN",
    USER_REGISTER: "USER_REGISTER"
    
}

export default actionType ;